Repository jenkinsci/dashboard-view-plugin, pull requests merged in 2020-11, with the labels that each got.

#70 Switch Release Drafter to a GitHub Action
  .github/workflows/changelog.yml
Labels: chore

#72 Make dependency on matrix-project plugin optional
  pom.xml
  src/main/java/hudson/plugins/view/dashboard/test/TestUtil.java
Labels: enhancement

#73 Add Dependabot configuration
  .github/dependabot.yml
Labels: chore

#87 Bump dependency versions to fix flaky tests
  pom.xml
Labels: chore, dependencies
