Repository jenkinsci/dashboard-view-plugin, pull requests merged in 2024-08, with the labels that each got.

#368 Remove hard-coded java-version in Security Scan
  .github/workflows/jenkins-security-scan.yml
Labels: chore, github_actions

#369 remove oneEach restriction
  src/main/resources/hudson/plugins/view/dashboard/Dashboard/configure-entries.jelly
Labels: bug

#367 Modernize to Jenkins 2.440.3
  pom.xml
Labels: chore
